services:
  # 1. Server come devcontainer (non avvia il programma)
  server-dev:
    build:
      context: .
      dockerfile: ./.devcontainer/server/Dockerfile.dev
    volumes:
      - ./server:/workspace/server
      - ./shared:/workspace/shared
    command: sleep infinity
    networks:
      - dungeon-net

  # 2. Esegue client Godot headless
  client-auto:
    build:
      context: .
      dockerfile: ./.devcontainer/client/Dockerfile.dev
    volumes:
      - ./client:/workspace/client
      - ./shared:/workspace/shared
    environment:
      - SERVER_IP=server-dev
      - SERVER_PORT=8080
      - ACTION
    command: godot --headless 
    networks:
      - dungeon-net

  # 3. Client Godot come devcontainer (non avvia il comando)
  client-dev:
    build:
      context: .
      dockerfile: ./.devcontainer/client/Dockerfile.dev
    volumes:
      - ./client:/workspace/client
      - ./shared:/workspace/shared
    environment:
      - SERVER_IP=server-dev
      - SERVER_PORT=8080
    command: sleep infinity
    networks:
      - dungeon-net

# 4. Server per produzione (mettere in un compose separato ???)
  server-prod:
    build:
      context: .
      dockerfile: server/Dockerfile.prod
    ports:
      - "8080:8080"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8080"]
      interval: 1m30s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - dungeon-net
    profiles:
      - prod

networks:
  dungeon-net:
    driver: bridge