FROM debian:bookworm

RUN apt-get update && apt-get install -y \
    build-essential \
    gdb \
    procps \
    htop \
    valgrind \
    strace \
    git \
    make \
    netcat-openbsd \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
COPY server/ ./server/
COPY shared/ ./shared/

WORKDIR /workspace/server
CMD ["make", "all"]