# ---------- build stage ----------
FROM debian:bookworm AS builder

RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /build

# copiamo server
COPY server /build/server

WORKDIR /build/server

RUN make compile_matchmaker compile_game


# ---------- runtime stage ----------
FROM debian:bookworm-slim

WORKDIR /app

# copiamo solo il binario
COPY --from=builder /build/server/bin .

# installiamo netcat per l'healthcheck
RUN apt-get update && apt-get install -y netcat-openbsd && rm -rf /var/lib/apt/lists/*

EXPOSE 8080

CMD ["./matchmaker"]