FROM debian:bookworm

RUN apt-get update && apt-get install -y \
    build-essential \
    gdb \
    valgrind \
    strace \
    git \
    make \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
COPY server/ ./server/
COPY shared/ ./shared/

CMD ["sleep", "infinity"]